name: CI

on:
    - pull_request

jobs:
    lint:
        name: Source code formatting & spellcheck
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Check formatting with Prettier
              run: yarn format:check

            # - name: Spellcheck
            #   run: yarn spellcheck

    typecheck:
        name: Typecheck & linting
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Lint with ESLint
              run: yarn lint

            - name: Check Typescript
              run: |
                  yarn typecheck